name: PixelSport Update

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install cloudscraper

      - name: Run script
        run: python pxl.py 

    - name: Commit and Push M3U
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add pixelsports.m3u8
        git commit -m "Update M3U: $(date -u)" || echo "No changes to commit"
        git push
